apiVersion: operator.openshift.io/v1
kind: Network
metadata:
  name: cluster
spec:
  additionalNetworks:
  - name: test-network-node0
    namespace: test-1
    rawCNIConfig: '{ "cniVersion": "0.3.1", "name": "test-network-node0", "type":
      "host-device", "device": "enp255s4" }'
    type: Raw
  - name: test-network-node1
    namespace: test-1
    rawCNIConfig: '{ "cniVersion": "0.3.1", "name": "test-network-node1", "type":
      "host-device", "device": "enp253s4" }'
    type: Raw
  clusterNetwork:
status: {}
