apiVersion: v1
kind: Pod
metadata:
  name: pod-numa1
  namespace: test-1
  annotations:
    k8s.v1.cni.cncf.io/networks: test-network-node1
spec:
  containers:
    - name: centos
      image: centos/tools
      command: [ "/bin/bash", "-c", "sleep infinity" ]
